services:
  # Backend service
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    networks:
      - app-network

  # Frontend service
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: app
    environment:
      - VITE_PROXY_TARGET=server
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - server

# Network configuration
networks:
  app-network:
    driver: bridge
